@echo off
REM Builds and runs tools/test-settingscache.cpp: the real DatabaseManager over an
REM in-memory SQLite database, checking that settings answered from memory are the
REM settings in the table. No network, no files.

call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat" >nul 2>&1

set QT=C:\Qt\6.5.3\msvc2019_64
cd /d "%~dp0"
set OUT=%TEMP%\casparcg-test-settingscache
if not exist "%OUT%" mkdir "%OUT%"

REM Version.h is generated by CMake; the manager only needs these two values.
> "%OUT%\Version.h" echo #pragma once
>> "%OUT%\Version.h" echo #define DATABASE_VERSION "0"
>> "%OUT%\Version.h" echo #define DEV_BUILD_ID "0"

cl /nologo /EHsc /std:c++17 /Zc:__cplusplus /permissive- /MD /W3 /DCORE_LIBRARY /DCOMMON_LIBRARY ^
   /Fo"%OUT%\\" /Fe"%OUT%\test-settingscache.exe" ^
   test-settingscache.cpp ..\src\Core\DatabaseManager.cpp ..\src\Core\Models\*.cpp ..\src\Common\Playout.cpp ^
   /I"%OUT%" /I..\src\Core /I..\src /I..\src\Common ^
   /I"%QT%\include" /I"%QT%\include\QtCore" /I"%QT%\include\QtSql" ^
   /link /LIBPATH:"%QT%\lib" Qt6Core.lib Qt6Sql.lib >"%OUT%\build.log" 2>&1
if errorlevel 1 (
    type "%OUT%\build.log" | findstr /i "error"
    exit /b 1
)

set PATH=%QT%\bin;%PATH%
"%OUT%\test-settingscache.exe"
